name: Build Backend Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
    branches:
      - main

jobs:
  build:
    name: backend:build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags:
            ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend-${{
            github.sha }}

  test:
    name: backend:test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and run tests
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend-${{ github.sha }}
          docker run -d -p 8080:8080 -e APP_PORT=8080 ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend-${{ github.sha }}
          sleep 10
          curl localhost:8080/api/status
          exit $?
      - name: Push image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend-${{ github.sha }} ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend
          docker push ghcr.io/${{ github.repository_owner }}/k8s-toyapp:backend
