name: Build Frontend Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'
    branches:
      - main

jobs:
  build:
    name: frontend:build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags:
            ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend-${{
            github.sha }}

  test:
    name: frontend:test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and run tests
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend-${{ github.sha }}
          docker run -d -p 8000:8000 ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend-${{ github.sha }}
          sleep 10
          curl localhost:8000/
          exit $?
      - name: Push image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend-${{ github.sha }} ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend
          docker push ghcr.io/${{ github.repository_owner }}/k8s-toyapp:frontend
